services:
  percona:
    image: percona:8.0.36-28
    environment:
      MYSQL_ROOT_PASSWORD: sql_root_pass
      MYSQL_DATABASE: test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: sql_root_pass
      MYSQL_DATABASE: test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  php-execute-percona:
    build:
      context: ./
      dockerfile: ./php.dockerfile
    command: php /repro.php
    restart: always
    environment:
      DB_HOST: percona
    volumes:
      - ./repro.php:/repro.php:ro
  php-execute-mysql:
    build:
      context: ./
      dockerfile: ./php.dockerfile
    command: php /repro.php
    restart: always
    environment:
      DB_HOST: mysql
    volumes:
      - ./repro.php:/repro.php:ro
